# tests/checks/test_pylock_fresh.py
# Copyright 2026 Nathan Ramos, CFA
# SPDX-License-Identifier: Apache-2.0
"""Unit tests for scripts/checks/pylock_fresh.py, the pylock.toml freshness check."""

from __future__ import annotations

import importlib.util
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from types import ModuleType

    import pytest

SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "checks" / "pylock_fresh.py"
HEADER = "# This file was autogenerated by uv via the following command:\n#    uv ...\n"
BODY = 'lock-version = "1.0"\ncreated-by = "uv"\n'


def load_script() -> ModuleType:
    spec = importlib.util.spec_from_file_location("pylock_fresh_check", SCRIPT)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


pylock_fresh = load_script()


def run(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, committed: str, fresh: str
) -> int:
    (tmp_path / "pylock.toml").write_text(committed, encoding="utf-8")
    monkeypatch.chdir(tmp_path)

    def which(_: str) -> str:
        return "uv"

    def export(_: str) -> str:
        return fresh

    monkeypatch.setattr(pylock_fresh.shutil, "which", which)
    monkeypatch.setattr(pylock_fresh, "export", export)
    result: int = pylock_fresh.main()
    return result


def test_body_drops_only_the_leading_header() -> None:
    assert pylock_fresh.body(HEADER + BODY + "# trailing\n") == BODY + "# trailing"


def test_matching_export_passes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert run(tmp_path, monkeypatch, HEADER + BODY, BODY) == 0


def test_stale_export_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert run(tmp_path, monkeypatch, HEADER + BODY, BODY + "[[packages]]\n") == 1
    assert "pylock.toml is stale" in capsys.readouterr().err


def test_the_committed_pylock_names_the_documented_command() -> None:
    # The real export runs in the prek hook; the suite stays offline and
    # uv-free, so it checks only that the header names the documented command.
    text = (SCRIPT.parents[2] / "pylock.toml").read_text(encoding="utf-8")
    assert text.startswith(HEADER.splitlines()[0])
    assert pylock_fresh.FIX in text.splitlines()[1]
