# src/pyeconomics/core/__init__.py
# Copyright 2026 Nathan Ramos, CFA
# SPDX-License-Identifier: Apache-2.0
"""The conventions every pyeconomics model encodes (ADR-0008).

This package holds numerical conventions, the date layer and the shared
numerics models build on: unit kinds and their
default bounds (:mod:`~pyeconomics.core.units`), percent and basis-point
conversion (:mod:`~pyeconomics.core.rates`), compounding
(:mod:`~pyeconomics.core.compounding`), tolerances
(:mod:`~pyeconomics.core.tolerance`), seeded randomness
(:mod:`~pyeconomics.core.random`), root finding
(:mod:`~pyeconomics.core.numerics`), cash-flow discounting and IRR
(:mod:`~pyeconomics.core.cashflows`), zero curves with forward and par rates
(:mod:`~pyeconomics.core.curves`), descriptive statistics
(:mod:`~pyeconomics.core.descriptive`), and the error and warning taxonomy
(:mod:`~pyeconomics.core.errors`, :mod:`~pyeconomics.core.warnings`). None of
it does I/O: no network, file, clock or environment access.

Examples
--------
>>> from pyeconomics.core import Compounding, Frequency, discount_factor
>>> round(discount_factor(0.04, 5, Compounding.PERIODIC, Frequency.SEMIANNUAL), 10)
0.8203482999

"""

from pyeconomics.core.calendars import (
    CALENDAR_IDS,
    BusinessDayConvention,
    CalendarId,
    add_business_days,
    adjust,
    is_business_day,
)
from pyeconomics.core.canonical import canonical_json, canonical_sha256
from pyeconomics.core.cards import ModelCard
from pyeconomics.core.cashflows import (
    IRR_LOWER,
    IRR_POLICY,
    IRR_UPPER,
    accumulated_annuity_factor,
    accumulated_growing_annuity_factor,
    annuity_factor,
    growing_annuity_factor,
    growing_perpetuity_factor,
    growth_factor,
    internal_rate_of_return,
    present_value,
    present_value_factor,
    sign_changes,
)
from pyeconomics.core.compounding import (
    Compounding,
    Frequency,
    accumulation_factor,
    convert_rate,
    discount_factor,
    effective_annual_rate,
    implied_rate,
)
from pyeconomics.core.context import collect_warnings, warn
from pyeconomics.core.curves import (
    curve_discount_factors,
    forward_rate,
    interpolate_rate,
    par_rate,
)
from pyeconomics.core.dates import (
    actual_days,
    add_months,
    add_years,
    is_end_of_month,
    validate_date,
)
from pyeconomics.core.daycount import DayCount, year_fraction
from pyeconomics.core.descriptive import (
    Drawdown,
    Moments,
    max_drawdown,
    sample_mean,
    sample_moments,
    sample_variance,
    semideviation_below_mean,
    semideviation_below_target,
)
from pyeconomics.core.errors import (
    ConvergenceError,
    DomainError,
    InputError,
    MissingOptionalDependencyError,
    ModelNotFoundError,
    PyeconomicsError,
    RegistryError,
)
from pyeconomics.core.manifest import Manifest
from pyeconomics.core.model import (
    ARRAY_INPUT,
    CorrelationArray,
    CountArray,
    DateArray,
    DaysArray,
    IndexLevelArray,
    Model,
    ModelInputs,
    ModelOutputs,
    MoneyArray,
    PeriodsArray,
    ProbabilityArray,
    RateArray,
    RatioArray,
    ReturnArray,
    VolatilityArray,
    YearsArray,
    model,
)
from pyeconomics.core.numerics import (
    DEFAULT_ROOT_POLICY,
    RootPolicy,
    RootResult,
    bracket_roots,
    find_root,
)
from pyeconomics.core.random import (
    BIT_GENERATOR,
    DEFAULT_SEED,
    SEED_MAX,
    SEED_MIN,
    RandomProvenance,
    generator,
    provenance,
)
from pyeconomics.core.rates import (
    BASIS_POINTS_PER_UNIT,
    PERCENT_PER_UNIT,
    basis_points_to_decimal,
    decimal_to_basis_points,
    decimal_to_percent,
    format_basis_points,
    format_percent,
    percent_to_decimal,
)
from pyeconomics.core.registry import (
    ENTRY_POINT_GROUP,
    Provider,
    Registry,
    discover,
)
from pyeconomics.core.results import BatchResult, Result, ResultWarning
from pyeconomics.core.runner import (
    MAX_BATCH_ROWS,
    run,
    run_batch,
    run_model,
    run_model_batch,
)
from pyeconomics.core.schedule import Schedule, generate
from pyeconomics.core.schema import input_schema, output_schema
from pyeconomics.core.spec import (
    DOMAINS,
    Alias,
    ChangelogEntry,
    ChartKind,
    ChartSpec,
    CostClass,
    Evidence,
    Example,
    Invariant,
    ModelSpec,
    Reference,
)
from pyeconomics.core.tolerance import (
    DEFAULT_TOLERANCES,
    EXACT,
    Tolerance,
    default_tolerance,
)
from pyeconomics.core.units import (
    DEFAULT_BOUNDS,
    DEFAULT_DATE_BOUNDS,
    MAX_ARRAY_LENGTH,
    MAX_STRING_LENGTH,
    UNIT_SCHEMA_KEY,
    Bounds,
    Correlation,
    Count,
    DateBounds,
    DateValue,
    Days,
    IndexLevel,
    Money,
    Periods,
    Probability,
    Rate,
    Ratio,
    Return,
    Unit,
    UnitKind,
    Volatility,
    Years,
    default_bounds,
)
from pyeconomics.core.warnings import (
    ModelWarning,
    PyeconomicsDeprecationWarning,
    PyeconomicsWarning,
    deprecated,
)

__all__ = [
    "ARRAY_INPUT",
    "BASIS_POINTS_PER_UNIT",
    "BIT_GENERATOR",
    "CALENDAR_IDS",
    "DEFAULT_BOUNDS",
    "DEFAULT_DATE_BOUNDS",
    "DEFAULT_ROOT_POLICY",
    "DEFAULT_SEED",
    "DEFAULT_TOLERANCES",
    "DOMAINS",
    "ENTRY_POINT_GROUP",
    "EXACT",
    "IRR_LOWER",
    "IRR_POLICY",
    "IRR_UPPER",
    "MAX_ARRAY_LENGTH",
    "MAX_BATCH_ROWS",
    "MAX_STRING_LENGTH",
    "PERCENT_PER_UNIT",
    "SEED_MAX",
    "SEED_MIN",
    "UNIT_SCHEMA_KEY",
    "Alias",
    "BatchResult",
    "Bounds",
    "BusinessDayConvention",
    "CalendarId",
    "ChangelogEntry",
    "ChartKind",
    "ChartSpec",
    "Compounding",
    "ConvergenceError",
    "Correlation",
    "CorrelationArray",
    "CostClass",
    "Count",
    "CountArray",
    "DateArray",
    "DateBounds",
    "DateValue",
    "DayCount",
    "Days",
    "DaysArray",
    "DomainError",
    "Drawdown",
    "Evidence",
    "Example",
    "Frequency",
    "IndexLevel",
    "IndexLevelArray",
    "InputError",
    "Invariant",
    "Manifest",
    "MissingOptionalDependencyError",
    "Model",
    "ModelCard",
    "ModelInputs",
    "ModelNotFoundError",
    "ModelOutputs",
    "ModelSpec",
    "ModelWarning",
    "Moments",
    "Money",
    "MoneyArray",
    "Periods",
    "PeriodsArray",
    "Probability",
    "ProbabilityArray",
    "Provider",
    "PyeconomicsDeprecationWarning",
    "PyeconomicsError",
    "PyeconomicsWarning",
    "RandomProvenance",
    "Rate",
    "RateArray",
    "Ratio",
    "RatioArray",
    "Reference",
    "Registry",
    "RegistryError",
    "Result",
    "ResultWarning",
    "Return",
    "ReturnArray",
    "RootPolicy",
    "RootResult",
    "Schedule",
    "Tolerance",
    "Unit",
    "UnitKind",
    "Volatility",
    "VolatilityArray",
    "Years",
    "YearsArray",
    "accumulated_annuity_factor",
    "accumulated_growing_annuity_factor",
    "accumulation_factor",
    "actual_days",
    "add_business_days",
    "add_months",
    "add_years",
    "adjust",
    "annuity_factor",
    "basis_points_to_decimal",
    "bracket_roots",
    "canonical_json",
    "canonical_sha256",
    "collect_warnings",
    "convert_rate",
    "curve_discount_factors",
    "decimal_to_basis_points",
    "decimal_to_percent",
    "default_bounds",
    "default_tolerance",
    "deprecated",
    "discount_factor",
    "discover",
    "effective_annual_rate",
    "find_root",
    "format_basis_points",
    "format_percent",
    "forward_rate",
    "generate",
    "generator",
    "growing_annuity_factor",
    "growing_perpetuity_factor",
    "growth_factor",
    "implied_rate",
    "input_schema",
    "internal_rate_of_return",
    "interpolate_rate",
    "is_business_day",
    "is_end_of_month",
    "max_drawdown",
    "model",
    "output_schema",
    "par_rate",
    "percent_to_decimal",
    "present_value",
    "present_value_factor",
    "provenance",
    "run",
    "run_batch",
    "run_model",
    "run_model_batch",
    "sample_mean",
    "sample_moments",
    "sample_variance",
    "semideviation_below_mean",
    "semideviation_below_target",
    "sign_changes",
    "validate_date",
    "warn",
    "year_fraction",
]
