name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: true

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          echo "__version__ = '${{ env.VERSION }}'" > pyeconomics/__version__.py

      - name: Install build dependencies
        run: pip install setuptools wheel
        continue-on-error: true

      - name: Install dependencies
        run: pip install -r requirements.txt
        continue-on-error: true

      - name: Build package
        run: python setup.py sdist bdist_wheel
        continue-on-error: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        continue-on-error: true
